<?xml version="1.0" encoding="utf-8"?><Database Name="LoginForm" Class="LinQBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-16PLU27\SQLEXPRESS;Initial Catalog=LoginForm;Integrated Security=True" SettingsObjectName="ClassLibrary1.Properties.Settings" SettingsPropertyName="LoginFormConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_chitiethd" Member="tbl_chitiethds">
    <Type Name="tbl_chitiethd">
      <Column Name="MAHD" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="tbl_kho_tbl_chitiethd" Member="tbl_kho" ThisKey="MASP" OtherKey="MASP" Type="tbl_kho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_chitietsp" Member="tbl_chitietsps">
    <Type Name="tbl_chitietsp">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MANHOM" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="tbl_nhomSP_tbl_chitietsp" Member="tbl_nhomSP" ThisKey="MANHOM" OtherKey="MANHOM" Type="tbl_nhomSP" IsForeignKey="true" />
      <Association Name="tbl_kho_tbl_chitietsp" Member="tbl_kho" ThisKey="MASP" OtherKey="MASP" Type="tbl_kho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_nhomSP" Member="tbl_nhomSPs">
    <Type Name="tbl_nhomSP">
      <Column Name="MANHOM" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="tbl_nhomSP_tbl_chitietsp" Member="tbl_chitietsps" ThisKey="MANHOM" OtherKey="MANHOM" Type="tbl_chitietsp" />
      <Association Name="tbl_nhomSP_tbl_kho" Member="tbl_khos" ThisKey="MANHOM" OtherKey="MANHOM" Type="tbl_kho" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_user" Member="tbl_users">
    <Type Name="tbl_user">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_user" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_chitiethdban" Member="tbl_chitiethdbans">
    <Type Name="tbl_chitiethdban">
      <Column Name="MAHD" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="tbl_kho_tbl_chitiethdban" Member="tbl_kho" ThisKey="MASP" OtherKey="MASP" Type="tbl_kho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_nhacungcap" Member="tbl_nhacungcaps">
    <Type Name="tbl_nhacungcap">
      <Column Name="MANCC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SLCHINHANH" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SLLOAIMATHANG" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_kho" Member="tbl_khos">
    <Type Name="tbl_kho">
      <Column Name="MASP" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DONVI" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANHOM" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tbl_kho_tbl_chitiethd" Member="tbl_chitiethds" ThisKey="MASP" OtherKey="MASP" Type="tbl_chitiethd" />
      <Association Name="tbl_kho_tbl_chitietsp" Member="tbl_chitietsps" ThisKey="MASP" OtherKey="MASP" Type="tbl_chitietsp" />
      <Association Name="tbl_kho_tbl_chitiethdban" Member="tbl_chitiethdbans" ThisKey="MASP" OtherKey="MASP" Type="tbl_chitiethdban" />
      <Association Name="tbl_nhomSP_tbl_kho" Member="tbl_nhomSP" ThisKey="MANHOM" OtherKey="MANHOM" Type="tbl_nhomSP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>