<?xml version="1.0" encoding="utf-8"?><Database Name="QLlogin" Class="LinQBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\QLlogin.mdf;Integrated Security=True" SettingsObjectName="DAL_Login.Properties.Settings" SettingsPropertyName="QLloginConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_per_relationship" Member="tbl_per_relationships">
    <Type Name="tbl_per_relationship">
      <Column Name="id_rel" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_user_rel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_per_rel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="suspended" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tbl_permisstion_tbl_per_relationship" Member="tbl_permisstion" ThisKey="id_per_rel" OtherKey="id_per" Type="tbl_permisstion" IsForeignKey="true" />
      <Association Name="tbl_user_tbl_per_relationship" Member="tbl_user" ThisKey="id_user_rel" OtherKey="id_user" Type="tbl_user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_permisstion" Member="tbl_permisstions">
    <Type Name="tbl_permisstion">
      <Column Name="id_per" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_per" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_permisstion_tbl_per_relationship" Member="tbl_per_relationships" ThisKey="id_per" OtherKey="id_per_rel" Type="tbl_per_relationship" />
      <Association Name="tbl_permisstion_tbl_permisstion_detail" Member="tbl_permisstion_details" ThisKey="id_per" OtherKey="id_per" Type="tbl_permisstion_detail" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_permisstion_detail" Member="tbl_permisstion_details">
    <Type Name="tbl_permisstion_detail">
      <Column Name="id_pd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_action" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="code_action" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_per" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_permisstion_tbl_permisstion_detail" Member="tbl_permisstion" ThisKey="id_per" OtherKey="id_per" Type="tbl_permisstion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_user" Member="tbl_users">
    <Type Name="tbl_user">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_user" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_user_tbl_per_relationship" Member="tbl_per_relationships" ThisKey="id_user" OtherKey="id_user_rel" Type="tbl_per_relationship" />
    </Type>
  </Table>
</Database>